### ISSUE TITLE
json.Number not handled

### ISSUE THREAD

**Issue by stuartleeks** [TylerBrock/colorjson#4]
The `encoding/json` library allows you to use the `Decoder` type to parse JSON and preserve the formatting of numbers using the `UseNumber` method. When doing this, colorjson fails to render the numbers in the output.

With the following code:

```go
package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"github.com/TylerBrock/colorjson"
)

func main() {
	str := `{
  "str": "foo",
  "num": 100.0,
  "bool": false,
  "null": null,
  "array": ["foo", "bar", "baz"],
  "obj": { "a": 1, "b": 2 }
}`

	d := json.NewDecoder(strings.NewReader(str))
	d.UseNumber()
	var obj interface{}
	_ = d.Decode(&obj)


	f := colorjson.NewFormatter()
	f.Indent = 2

	s, _ := colorjson.Marshal(obj)
	fmt.Println(string(s))

}
```

The output is shown below (note the absence of any numeric values

```json
{ "array": [ "foo", "bar", "baz" ], "bool": false, "null": null, "num": , "obj": { "a": , "b":  }, "str": "foo" } 
```

The expected output is below (note that `num` is rendered as `100.0` rather than `100` as it would have been output without the `UseNumber` call)

```json
{ "array": [ "foo", "bar", "baz" ], "bool": false, "null": null, "num": 100.0, "obj": { "a": 1, "b": 2 }, "str": "foo" }
```

**Comment by Egrn** [comment]
> The `encoding/json` library allows you to use the `Decoder` type to parse JSON and preserve the formatting of numbers using the `UseNumber` method. When doing this, colorjson fails to render the numbers in the output.
> 
> With the following code:
> 
> ```go
> package main
> 
> import (
> 	"encoding/json"
> 	"fmt"
> 	"strings"
> 	"github.com/TylerBrock/colorjson"
> )
> 
> func main() {
> 	str := `{
>   "str": "foo",
>   "num": 100.0,
>   "bool": false,
>   "null": null,
>   "array": ["foo", "bar", "baz"],
>   "obj": { "a": 1, "b": 2 }
> }`
> 
> 	d := json.NewDecoder(strings.NewReader(str))
> 	d.UseNumber()
> 	var obj interface{}
> 	_ = d.Decode(&obj)
> 
> 
> 	f := colorjson.NewFormatter()
> 	f.Indent = 2
> 
> 	s, _ := colorjson.Marshal(obj)
> 	fmt.Println(string(s))
> 
> }
> ```
> 
> The output is shown below (note the absence of any numeric values
> 
> ```json
> { "array": [ "foo", "bar", "baz" ], "bool": false, "null": null, "num": , "obj": { "a": , "b":  }, "str": "foo" } 
> ```
> 
> The expected output is below (note that `num` is rendered as `100.0` rather than `100` as it would have been output without the `UseNumber` call)
> 
> ```json
> { "array": [ "foo", "bar", "baz" ], "bool": false, "null": null, "num": 100.0, "obj": { "a": 1, "b": 2 }, "str": "foo" }
> ```


I could not push branch with fix for uint64, but replacement behind workfull
```
func (f *Formatter) marshalValue(val interface{}, buf *bytes.Buffer, depth int) {
    switch v := val.(type) {
    case map[string]interface{}:
        f.marshalMap(v, buf, depth)
    case []interface{}:
        f.marshalArray(v, buf, depth)
    case string:
        f.marshalString(v, buf)
    case float64:
        buf.WriteString(f.sprintColor(f.NumberColor, strconv.FormatFloat(v, 'f', -1, 64)))
    **case uint64:
        buf.WriteString(f.sprintColor(f.NumberColor, strconv.FormatUint(v, 10)))**
    case bool:
        buf.WriteString(f.sprintColor(f.BoolColor, (strconv.FormatBool(v))))
    case nil:
        buf.WriteString(f.sprintColor(f.NullColor, null))
    }
}
```

**Comment by TylerBrock** [comment]
Should be fixed in the next release, sorry for the delay!
